<script setup lang="ts">
import { ref, computed } from 'vue';

interface Todo{
  id: number
  text: string
  completed: boolean
}

type FilterType = "all" | "active" | "completed"

const newTodoText = ref<string>("")
const filter = ref<FilterType>("all")

const todos = ref<Todo[]>([
  {id: 1, text: "sleep", completed: true},
  {id:2, text: "prepare lunch", completed:false}
])

// create new task
const addTodo =(): void =>{
  const text = newTodoText.value.trim()
  if(!text) return

  todos.value.push({
    id: Date.now(),
    text,
    completed:false
  })
  newTodoText.value = ""

}

// delete task

const removeTodo = (id: number): void =>{
  todos.value = todos.value.filter(todo => todo.id != id)
}

const filteredTodos = computed<Todo[]>(() => {
  if(filter.value === "active"){
    return todos.value.filter(t=> !t.completed)
  }
  if (filter.value === "completed"){
    return todos.value.filter(t => t.completed)
  }
  return todos.value
}) 

const remainingCount = computed<number>(() =>{
  return todos.value.filter(t  => !t.completed). length
})
</script>
<template>
  <div class="todo-app">
    <h1>Todo List</h1>

    <!--form input and send--->
    <form @submit.prevent="addTodo" class="input-form">
      <input type="text" placeholder="write new task here"
             v-model="newTodoText"/>
      <button type="submit">ADD</button>
    </form>

    <!--filter buttons-->
    <div class="filters">
      <button :class="{active: filter === 'all'}" 
              @click="filter = 'all'">ALL</button>
      <button :class="{active: filter === 'active'}"
              @click="filter = 'active'">NOT COMPLETED</button>
      <button :class="{active: filter === 'completed'}"
              @click="filter = 'completed'">COMPLETED</button>
    </div>

    <!-- show lists-->
    <ul class="todo-list">
      <li v-for="todo in filteredTodos" :key="todo.id" :class="{completed : todo.completed}">
        <label>
          <input type="checkbox" v-model="todo.completed" />
          <span>{{ todo.text }}</span>
        </label>
        <button @click="removeTodo(todo.id)" class="delete-btn">DELETE</button>
      </li>
    </ul>

    <!--show remaining tasks number-->
    <footer class="footer">
      <span> here are remaining tasks: {{remainingCount}}</span>
    </footer>

  </div>
</template>

<!-- this project purpuse is to learn vue3 with typescript, 
so CSS is generated by AI -->
<style scoped>
.todo-app {
  max-width: 400px;
  margin: 2rem auto;
  padding: 1.5rem;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  font-family: sans-serif;
}

.input-form {
  display: flex;
  gap: 8px;
  margin-bottom: 1rem;
}

.input-form input {
  flex: 1;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 4px;
}

.filters {
  display: flex;
  gap: 8px;
  margin-bottom: 1rem;
}

.filters button {
  padding: 4px 8px;
  border: 1px solid #ddd;
  background: #f5f5f5;
  cursor: pointer;
  border-radius: 4px;
}

.filters button.active {
  background: #42b883;
  color: white;
  border-color: #42b883;
}

.todo-list {
  list-style: none;
  padding: 0;
  margin: 0;
}

.todo-list li {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 8px 0;
  border-bottom: 1px solid #eee;
}

.todo-list li.completed span {
  text-decoration: line-through;
  color: #888;
}

.delete-btn {
  background: #ff5252;
  color: white;
  border: none;
  padding: 4px 8px;
  border-radius: 4px;
  cursor: pointer;
}

.footer {
  margin-top: 1rem;
  font-size: 0.9rem;
  color: #666;
}
</style>